### ISSUE TITLE
Sync all vs sync selected contacts

### ISSUE THREAD

**Issue by Vinne2** [loadrunner/Facebook-Contact-Sync#23]
I ran it for the 1st time and it seems it will sync all at once so I stopped the 1st sync (see post scriptum). But 1) some of my contacts have set weird photos or not their photos as their profile picture 2) I already have locally a better picture for them - so I don't want to change current photo to one from facebook. The app will be gorgeous if I could select some contacts, not all. Thanks :)

P.S.
I hate that it starts sync with default options on first run automatically without even asking! How about user setting some options before running sync, he?

**Comment by loadrunner** [comment]
This project was discontinued. Facebook doesn't support this feature any more. Sorry.
