### ISSUE TITLE
use facebook groups as address book contact groups

### ISSUE THREAD

**Issue by neniuideo** [loadrunner/Facebook-Contact-Sync#25]
I want suggest the following feature...

All facebook contacts belong now to the group "Friends" at my android address book, it would be great if the facebook contacts use the same groups names as the friends in facebook (the friends in facebook are sorted within the facebook groups).

If this are not possible (may facebook do not allow to access this info) it would be great if (optional) there are no group name. Because an group named "Friends" are useless on my android address book.

**Comment by loadrunner** [comment]
This project was discontinued. Facebook doesn't support this feature any more. Sorry.
