### ISSUE TITLE
Pictures won't sync

### ISSUE THREAD

**Issue by David93X** [loadrunner/Facebook-Contact-Sync#27]
I'm using Cyanogenmod 10.2 on SIII Mini:

Sync Type: Hard
Sync all contacts

Every Other Details are being synced correctly but pictures, they don't appear at all.
Tried different picture sizes but still not working
Although it worked few days ago on the same ROM

**Comment by loadrunner** [comment]
This project was discontinued. Facebook doesn't support this feature any more. Sorry.
