### ISSUE TITLE
Contacts Not imported properly 

### ISSUE THREAD

**Issue by dhanasekaran-anbalagan** [loadrunner/Facebook-Contact-Sync#36]
Hi Guys,

I am using this app, version 2.2.0 with moto E contacts not updated properly,  But it says that 237 contacts imported.

My question: 

where actually imported contacts. [phone memory / SD card]

can you guide me..

**Comment by loadrunner** [comment]
This project was discontinued. Facebook doesn't support this feature any more. Sorry.
