### ISSUE TITLE
Ubersync contact can not join to an existing contact 

### ISSUE THREAD

**Issue by Zylazy** [loadrunner/Facebook-Contact-Sync#42]
I have reinstalled my phone, and I had to resync my phone book. Most of the contacts are joined automatically, but some of them are not, because they have different names in my google account and on facebook.
I have changed to setting: display only Ubersync contact, which are Ungrouped. Then I wanted to link them manually, but when I open them for editing and click the Join option, then I get an "Unfortunately, Contacts has stopped." error message.
If I do backwards (open the contact from my google account, and click join) then I can link them together.

**Comment by loadrunner** [comment]
This project was discontinued. Facebook doesn't support this feature any more. Sorry.
