### ISSUE TITLE
It works but the settings page / app crashes

### ISSUE THREAD

**Issue by valerio-bozzolan** [loadrunner/Facebook-Contact-Sync#43]
The sync works but when I open the app from the icon in the app list, it crashes; even when I open it from the "Account setting" in the Account part.

:|

Samsung Galaxy Nexus 4.4.4 (Paranoid Android)

App version 2.1.1 (F-Droid)

**Comment by loadrunner** [comment]
This project was discontinued. Facebook doesn't support this feature any more. Sorry.
