### ISSUE TITLE
Doesn't join to existing contacts

### ISSUE THREAD

**Issue by coldpumpkin** [loadrunner/Facebook-Contact-Sync#47]
Basically it's loading the facebook contacts but it's not joining them with the existing contacts on the phone. Are we supposed to join them manually?

Using Android 4.4.

**Comment by protist** [comment]
It used to automatically merge into existing contacts perfectly, but recently (in the last month or so?) it keeps them separate. Oddly enough, contacts that I have manually tagged with the facebook ID in the notes field are merged fine. This makes the app non-functional, as the images are kept separate from the contacts' information.

**Comment by sulate** [comment]
Same here. Matching names but no merge. Very annoying. Android 4.4.4 (oneplus/cyanogenmod).

**Comment by loadrunner** [comment]
This project was discontinued. Facebook doesn't support this feature any more. Sorry.

**Comment by protist** [comment]
FWIW, HaxSync works well.
https://play.google.com/store/apps/details?id=org.mots.haxsync&hl=en

**Comment by loadrunner** [comment]
Are you sure?
Maybe he's got some inside deal with Facebook, dunno.
But officially there's not way to do it with the new API.
I talked with someone from Facebook about this and he said I should retire the app.

**Comment by protist** [comment]
I ran HaxSync for a few days to check, and yes, I think you are right. It's not updating, and failing silently. I didn't try removing my contacts and re-syncing, because I'm worried that it will lose what information I have, but it does seem like it's not functional any more.
