### ISSUE TITLE
Ubersync application stops instantly after start

### ISSUE THREAD

**Issue by JonathanWallace45** [loadrunner/Facebook-Contact-Sync#48]
I had ubersync installed on my fairphone and it worked perfectly.
I rerooted and restored to factory settings for reasons that have nothing to do with ubersync.
Now I installed Ubersync from F-Droid but when I start the application it shows a black screen with the Ubersync for facebook title and then instantly a popup tells me that the application has stopped.

Any ideas on what's happening ?

**Comment by martinruenz** [comment]
I do have the same issue using a HTC One with Android 4.4.2. Like Jonathan I also got the appliction from F-Droid.

**Comment by haeckle** [comment]
I got the same problem with CyanogenMod 12 on an unrooted Motorola Moto G 2014. Installation was also via F-Droid.

**Comment by loadrunner** [comment]
This project was discontinued. Facebook doesn't support this feature any more. Sorry.
