### ISSUE TITLE
Feature request: Actually replace the Google contact pictures

### ISSUE THREAD

**Issue by Linuspogo** [loadrunner/Facebook-Contact-Sync#52]
Hi,

instead of adding the UberSync accounts to the Google contacts accounts, it would be really nice to have the option to actually replace the Google contacts profile pictures, so that they also appear on other devices and the Google contacts web view.

Maybe someone with more programming skills than myself would like to implement that? ;)

Thanks!

**Comment by loadrunner** [comment]
This project was discontinued. Facebook doesn't support this feature any more. Sorry.
